/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2019 - 2020 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel Corporation
 * or its licensors. The Material contains trade secrets and proprietary
 * and confidential information of Intel or its licensors. The Material
 * is protected by worldwide copyright and trace secret laws and treaty
 * provisions. No part of the Material may beused, copied, reproduced,
 * modified, published, uploaded, posted, transmitted, distributed, or
 * disclosed in any way without Intel's prior express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 *
 */

/*
 * TODO: Adapt this file for IPU6!
 */

#ifndef __IA_CSS_PSA_PARAMETER_DEFS_DEP_H
#define __IA_CSS_PSA_PARAMETER_DEFS_DEP_H

/* Platform specific terminal specs. Common specs across platforms are defined in
 * ia_css_psa_parameter_defs.h
 */

#define IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_BNLM                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_GLTM_GLTM                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_LFE                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_VHF                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_HF                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_HF_SE                           (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_MF                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_MF_SE                           (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_LF                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_LF_SE                           (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_VLF                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_XNR5_VLF_SE                          (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_GLIM                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_GAMMASTAR                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ESPA                                 (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_GTC_GTM                              (0)

#define IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_BNLM                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_GLTM_GLTM                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_LFE                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_VHF                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_HF                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_HF_SE                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_MF                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_MF_SE                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_LF                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_LF_SE                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_VLF                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_XNR5_VLF_SE                           (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_GLIM                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_GAMMASTAR                             (1)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ESPA                                  (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_GTC_GTM                               (0)

#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_BNLM                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_GLTM_GLTM                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_LFE                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_VHF                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_HF                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_HF_SE                           (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_MF                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_MF_SE                           (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_LF                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_LF_SE                           (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_VLF                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_XNR5_VLF_SE                          (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_GLIM                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_GAMMASTAR                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ESPA                                 (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_GTC_GTM                              (0)

/* ==================== GTC_GTM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_0          (0x4)

#ifdef HRT_HW
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_0       (0x1c6c)
#else
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_0       (0x758)
#endif

#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_1          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_1       (0x75C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_2          (0x758)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_2       (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GTC_GTM_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for GTC_GTM */

/* Spatial Parameter Terminal Out does not exist for GTC_GTM */

#define IA_CSS_PSA_PROGRAM_TERMINAL_GTC_GTM_SECTION_COUNT                 (0)
/* ==================== GTC_GTM specs - END ==================== */

/* ==================== RYNR_BNLM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_SECTION_COUNT                (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_MAX_SIZE_SECTION_0           (0x0354)
#define IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_DEST_OFFSET_SECTION_0        (0x0000)

/* Spatial Parameter Terminal In does not exist for RYNR_BNLM */

/* Spatial Parameter Terminal Out does not exist for RYNR_BNLM */
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_BNLM_V3_SECTION_COUNT            (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_SECTION_COUNT                  (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_MAX_SIZE_SECTION_0             (0x000C)
#define IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_DEST_OFFSET_SECTION_0          (0x0380)

/* BNLM_VERSION_V1 (Default) */

/* Spatial Parameter Terminal In does not exist for RYNR_BNLM */

/* Spatial Parameter Terminal Out does not exist for RYNR_BNLM */
/* ==================== RYNR_BNLM specs - END ==================== */

/* ==================== GLTM_GLTM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_DEST_OFFSET_SECTION_0       (0x300)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_MAX_SIZE_SECTION_1          (0x38)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_DEST_OFFSET_SECTION_1       (0x304)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_MAX_SIZE_SECTION_2          (0x300)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GLTM_GLTM_DEST_OFFSET_SECTION_2       (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GLTM_GLTM_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for GLTM_GLTM */

/* Spatial Parameter Terminal Out does not exist for GLTM_GLTM */

#define IA_CSS_PSA_PROGRAM_TERMINAL_GLTM_GLTM_SECTION_COUNT                 (0)
/* ==================== GLTM_GLTM specs - END ==================== */

/* ==================== XNR5_LFE specs - START ==================== */
/* XNR5_LFE contains the top-level enable/disable functionality */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LFE_SECTION_COUNT              (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LFE_MAX_SIZE_SECTION_0         (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LFE_DEST_OFFSET_SECTION_0      (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LFE_MAX_SIZE_SECTION_1         (0x18)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LFE_DEST_OFFSET_SECTION_1      (0x8)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_LFE_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LFE_SECTION_COUNT                (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LFE_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LFE_DEST_OFFSET_SECTION_0        (0x0)

/* Spatial Parameter Terminal In does not exist for XNR5_LFE */

/* Spatial Parameter Terminal Out does not exist for XNR5_LFE */

/* ==================== XNR5_LFE specs - END ==================== */

/* ==================== XNR5_VHF specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_SECTION_COUNT              (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_MAX_SIZE_SECTION_0         (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_DEST_OFFSET_SECTION_0      (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_MAX_SIZE_SECTION_1         (0x8)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_DEST_OFFSET_SECTION_1      (0x8)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_MAX_SIZE_SECTION_2         (0x3C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VHF_DEST_OFFSET_SECTION_2      (0x1C)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_VHF_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VHF_SECTION_COUNT                (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VHF_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VHF_DEST_OFFSET_SECTION_0        (0x0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VHF_MAX_SIZE_SECTION_1           (0xC)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VHF_DEST_OFFSET_SECTION_1        (0x10)

/* Spatial Parameter Terminal In does not exist for XNR5_VHF */

/* Spatial Parameter Terminal Out does not exist for XNR5_VHF */

/* ==================== XNR5_VHF specs - END ==================== */

/* ==================== XNR5_HF specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_DEST_OFFSET_SECTION_0       (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_MAX_SIZE_SECTION_1          (0x14)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_DEST_OFFSET_SECTION_1       (0x8)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_MAX_SIZE_SECTION_2          (0x178)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_DEST_OFFSET_SECTION_2       (0x28)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_HF_SECTION_COUNT           (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_SECTION_COUNT                 (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_MAX_SIZE_SECTION_0            (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_DEST_OFFSET_SECTION_0         (0x0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_MAX_SIZE_SECTION_1            (0xC)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_DEST_OFFSET_SECTION_1         (0x1C)

/* Spatial Parameter Terminal In does not exist for XNR5_HF */

/* Spatial Parameter Terminal Out does not exist for XNR5_HF */

/* ==================== XNR5_HF specs - END ==================== */

/* ==================== XNR5_HF_SE specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_SE_SECTION_COUNT            (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_SE_MAX_SIZE_SECTION_0       (0x180)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_HF_SE_DEST_OFFSET_SECTION_0    (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_HF_SE_SECTION_COUNT        (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_HF_SE_SECTION_COUNT              (0)

/* Spatial Parameter Terminal In does not exist for XNR5_HF_SE */

/* Spatial Parameter Terminal Out does not exist for XNR5_HF_SE */

/* ==================== XNR5_HF_SE specs - END ==================== */

/* ==================== XNR5_MF specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_DEST_OFFSET_SECTION_0       (0x4)
/* Registers with offset 0x8 to 0x1C are not used */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_MAX_SIZE_SECTION_1          (0x1C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_DEST_OFFSET_SECTION_1       (0x20)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_MAX_SIZE_SECTION_2          (0x19C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_DEST_OFFSET_SECTION_2       (0x48)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_MF_SECTION_COUNT           (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_SECTION_COUNT                 (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_MAX_SIZE_SECTION_0            (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_DEST_OFFSET_SECTION_0         (0x0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_MAX_SIZE_SECTION_1            (0xC)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_DEST_OFFSET_SECTION_1         (0x3C)

/* Spatial Parameter Terminal In does not exist for XNR5_MF */

/* Spatial Parameter Terminal Out does not exist for XNR5_MF */

/* ==================== XNR5_MF specs - END ==================== */

/* ==================== XNR5_MF_SE specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_SE_SECTION_COUNT            (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_SE_MAX_SIZE_SECTION_0       (0x180)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_MF_SE_DEST_OFFSET_SECTION_0    (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_MF_SE_SECTION_COUNT        (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_MF_SE_SECTION_COUNT              (0)

/* Spatial Parameter Terminal In does not exist for XNR5_MF_SE */

/* Spatial Parameter Terminal Out does not exist for XNR5_MF_SE */

/* ==================== XNR5_MF_SE specs - END ==================== */

/* ==================== XNR5_LF specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_DEST_OFFSET_SECTION_0       (0x4)
/* Registers with offset 0x8 to 0x1C are not used */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_MAX_SIZE_SECTION_1          (0x1C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_DEST_OFFSET_SECTION_1       (0x20)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_MAX_SIZE_SECTION_2          (0x180)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_DEST_OFFSET_SECTION_2       (0x48)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_LF_SECTION_COUNT           (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_SECTION_COUNT                 (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_MAX_SIZE_SECTION_0            (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_DEST_OFFSET_SECTION_0         (0x0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_MAX_SIZE_SECTION_1            (0xC)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_DEST_OFFSET_SECTION_1         (0x3C)

/* Spatial Parameter Terminal In does not exist for XNR5_LF */

/* Spatial Parameter Terminal Out does not exist for XNR5_LF */

/* ==================== XNR5_LF specs - END ==================== */

/* ==================== XNR5_LF_SE specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_SE_SECTION_COUNT            (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_SE_MAX_SIZE_SECTION_0       (0x180)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_LF_SE_DEST_OFFSET_SECTION_0    (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_LF_SE_SECTION_COUNT        (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_LF_SE_SECTION_COUNT              (0)

/* Spatial Parameter Terminal In does not exist for XNR5_LF_SE */

/* Spatial Parameter Terminal Out does not exist for XNR5_LF_SE */

/* ==================== XNR5_LF_SE specs - END ==================== */

/* ==================== XNR5_VLF specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_SECTION_COUNT              (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_MAX_SIZE_SECTION_0         (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_DEST_OFFSET_SECTION_0      (0x4)
/* Registers with offset 0x8 to 0x2C are not used */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_MAX_SIZE_SECTION_1         (0x1C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_DEST_OFFSET_SECTION_1      (0x30)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_MAX_SIZE_SECTION_2         (0x148)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_DEST_OFFSET_SECTION_2      (0x58)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_VLF_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_SECTION_COUNT                (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_DEST_OFFSET_SECTION_0        (0x0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_MAX_SIZE_SECTION_1           (0xC)
#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_DEST_OFFSET_SECTION_1        (0x4C)

/* Spatial Parameter Terminal In does not exist for XNR5_VLF */

/* Spatial Parameter Terminal Out does not exist for XNR5_VLF */

/* ==================== XNR5_VLF specs - END ==================== */

/* ==================== XNR5_VLF_SE specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_SE_SECTION_COUNT           (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_SE_MAX_SIZE_SECTION_0      (0x180)
#define IA_CSS_PSA_PARAMETER_TERMINAL_XNR5_VLF_SE_DEST_OFFSET_SECTION_0   (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_XNR5_VLF_SE_SECTION_COUNT       (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_XNR5_VLF_SE_SECTION_COUNT             (0)

/* Spatial Parameter Terminal In does not exist for XNR5_VLF_SE */

/* Spatial Parameter Terminal Out does not exist for XNR5_VLF_SE */

/* ==================== XNR5_VLF_SE specs - END ==================== */

/* ==================== WBA_WBA specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_B2B_WBA_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_B2B_WBA_MAX_SIZE_SECTION_0          (0x20)
#define IA_CSS_PSA_PARAMETER_TERMINAL_B2B_WBA_DEST_OFFSET_SECTION_0       (0x0)
/* ==================== WBA_WBA specs - END ==================== */

/* ==================== ACM_GLIM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_SECTION_COUNT               (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_DEST_OFFSET_SECTION_0       (0x300)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_MAX_SIZE_SECTION_1          (0x24)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_DEST_OFFSET_SECTION_1       (0x304)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_MAX_SIZE_SECTION_2          (0x300)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_GLIM_DEST_OFFSET_SECTION_2       (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_GLIM_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for ACM_GLIM */

/* Spatial Parameter Terminal Out does not exist for ACM_GLIM */

#define IA_CSS_PSA_PROGRAM_TERMINAL_ACM_GLIM_SECTION_COUNT                 (0)
/* ==================== ACM_GLIM specs - END ==================== */

/* ==================== VCA_ACM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT                (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0        (0x0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1           (0x358)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1        (0x4)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT            (0)

/* Spatial Parameter Terminal In does not exist for VCA_ACM */

/* Spatial Parameter Terminal Out does not exist for VCA_ACM */
/* TODO: probably need to add program parameter here at 0x85C */
#define IA_CSS_PSA_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT                  (0)
/* ==================== VCA_ACM specs - END ==================== */

/* ==================== DEMOSAIC_DEMOSAIC specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0          (0x30)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0       (0x4)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for DEMOSAIC_DEMOSAIC */

/* Spatial Parameter Terminal Out does not exist for DEMOSAIC_DEMOSAIC */

#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT                 (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0            (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0         (0x0)
/* ==================== DEMOSAIC_DEMOSAIC specs - END ==================== */

/* ==================== GammaStar specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_GAMMASTAR_SECTION_COUNT                       (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GAMMASTAR_MAX_SIZE_SECTION_0                  (0xC8)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GAMMASTAR_DEST_OFFSET_SECTION_0               (0x8)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GAMMASTAR_SECTION_COUNT                   (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_GAMMASTAR_SECTION_COUNT                         (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_GAMMASTAR_MAX_SIZE_SECTION_0                    (0x8)
#define IA_CSS_PSA_PROGRAM_TERMINAL_GAMMASTAR_DEST_OFFSET_SECTION_0                 (0x0)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_SECTION_COUNT            (1)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_COMPUTE_UNITS_PER_ELEM             (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MAX_COMPUTE_UNITS_PER_SLICE        (145)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH   (2)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (145)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT  (2)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (109)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_MAX_SLICE_SIZE_SECTION_0           (0x18EC)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_ELEM_SIZE_SECTION_0                (0x2C)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_SLICE_0_DEST_OFFSET_SECTION_0      (0x100)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_GAMMASTAR_NEXT_SLICE_OFFSET_SECTION_0        (0x1900)

/* Spatial Parameter Terminal Out does not exist for GAMMASTAR */

/* ==================== GammaStar specs - END ==================== */

/* ==================== YUV1_IEFD specs - START ==================== */
/* Note: multiple version are defined */
/* IEFD_INTERFACE_VERSION_X (Default) */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT              (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_0         (0x0004)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_0      (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_1         (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_1      (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_2         (0x0074)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_2      (0x0074)

/* Spatial Parameter Terminal In does not exist for YUV1_IEFD */

/* Spatial Parameter Terminal Out does not exist for YUV1_IEFD */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT                (0)

/* IEFD_INTERFACE_VERSION_X_1 */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT            (4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0       (0x0004)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0    (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_1       (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_1    (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_2       (0x0034)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_2    (0x0074)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_3       (0x0034)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_3    (0x00B4)

/* Spatial Parameter Terminal In does not exist for YUV1_IEFD */

/* Spatial Parameter Terminal Out does not exist for YUV1_IEFD */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_1_SECTION_COUNT        (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT              (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0         (0x000C)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0      (0x00A8)
/* ==================== YUV1_IEFD specs - END ==================== */

/* ==================== DVS specs - START ==================== */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE        (154)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE       (154)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE        (120)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE       (120)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE        (85)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE       (85)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT                     (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT                     (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT                     (1)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (22) /*L0 grid_width* grid_height <= 154 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (22) /*L0 grid_width* grid_height <= 154 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (20) /*L1 grid_width* grid_height <= 120 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (20) /*L1 grid_width* grid_height <= 120 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (17) /*L2 grid_width* grid_height <= 85 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (17) /*L2 grid_width* grid_height <= 85 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)

/********************************** DVS MV Level 0 Specs start ******************************************/
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SECTION_COUNT                     (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_PER_SLICE       (22)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_PER_SLICE)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16) /*L0 grid_width* grid_height <= 154 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SLICE_0_DEST_OFFSET_SECTION_0     (0x4200)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_ELEM_SIZE_SECTION_0               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SET0_SET1_OFF_DIFF                (0x20) /* offset difference between Set0 base address + Set0 size and Set1 base offset */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_NEXT_SLICE_OFFSET_SECTION_0       (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_SLICE_SIZE_SECTION_0 + IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SET0_SET1_OFF_DIFF)
/********************************** DVS MV Level 0 Specs end ********************************************/

/********************************** DVS MV Level 1 Specs start ******************************************/
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SECTION_COUNT                     (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_PER_SLICE       (20)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_PER_SLICE)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16) /*L1 grid_width* grid_height <= 120 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SLICE_0_DEST_OFFSET_SECTION_0     (0x4500)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_ELEM_SIZE_SECTION_0               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SET0_SET1_OFF_DIFF                (0x0) /* offset difference between Set0 base address + Set0 size and Set1 base offset */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_NEXT_SLICE_OFFSET_SECTION_0       (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_SLICE_SIZE_SECTION_0 + IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SET0_SET1_OFF_DIFF)
/********************************** DVS MV Level 1 Specs end ********************************************/

/********************************** DVS MV Level 2 Specs start ******************************************/
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SECTION_COUNT                     (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_PER_SLICE       (17)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_PER_SLICE)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16) /*L2 grid_width* grid_height <= 85 */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SLICE_0_DEST_OFFSET_SECTION_0     (0x4780)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_ELEM_SIZE_SECTION_0               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SET0_SET1_OFF_DIFF                (0x30) /* offset difference between Set0 base address + Set0 size and Set1 base offset */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_NEXT_SLICE_OFFSET_SECTION_0       (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_SLICE_SIZE_SECTION_0 + IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SET0_SET1_OFF_DIFF)
/********************************** DVS MV Level 2 Specs end ********************************************/

#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SECTION_COUNT                     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_COMPUTE_UNITS_PER_ELEM            IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_PER_SLICE       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_SLICE_SIZE_SECTION_0          IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_ELEM_SIZE_SECTION_0               IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SLICE_0_DEST_OFFSET_SECTION_0     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L0_NEXT_SLICE_OFFSET_SECTION_0

#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SECTION_COUNT                     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_COMPUTE_UNITS_PER_ELEM            IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_PER_SLICE       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_SLICE_SIZE_SECTION_0          IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_ELEM_SIZE_SECTION_0               IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SLICE_0_DEST_OFFSET_SECTION_0     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L1_NEXT_SLICE_OFFSET_SECTION_0

#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SECTION_COUNT                     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_COMPUTE_UNITS_PER_ELEM            IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_PER_SLICE       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_SLICE_SIZE_SECTION_0          IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_ELEM_SIZE_SECTION_0               IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SLICE_0_DEST_OFFSET_SECTION_0     IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_MV_L2_NEXT_SLICE_OFFSET_SECTION_0
/* ==================== DVS specs - END ==================== */

#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_SECTION_COUNT					IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_0				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_0				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_1				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_1				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_2				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_MAX_SIZE_SECTION_2
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_2				IA_CSS_PSA_PARAMETER_TERMINAL_GTC_GTM_DEST_OFFSET_SECTION_2
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_GTC_GTM_SECTION_COUNT				IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GTC_GTM_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_GTC_GTM_SECTION_COUNT					IA_CSS_PSA_PROGRAM_TERMINAL_GTC_GTM_SECTION_COUNT
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_GTC_GTM							IA_CSS_PSA_KERNEL_IS_PRIMARY_GTC_GTM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_GTC_GTM							IA_CSS_PSA_NEEDS_SPATIAL_IN_GTC_GTM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_GTC_GTM							IA_CSS_PSA_NEEDS_SPATIAL_OUT_GTC_GTM

#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_BNLM_V3_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_BNLM_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_BNLM_V3_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_BNLM_V3_DEST_OFFSET_SECTION_0

#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT                   IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT               IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT                     IA_CSS_PSA_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0

#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_2    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_2
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_2 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_2
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_3    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_3
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_3 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_3
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_IEFD_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_1_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0

#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_RYNR_BNLM                                IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_BNLM
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_ACM_ACM                                  IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_RYNR_BNLM                                 IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_BNLM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_ACM_ACM                                   IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_RYNR_BNLM                                IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_BNLM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_ACM_ACM                                  IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM

/* END OF TODO */

#endif /* __IA_CSS_PSA_PARAMETER_DEFS_DEP_H */
