/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2015 - 2017 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel Corporation
 * or its licensors. The Material contains trade secrets and proprietary
 * and confidential information of Intel or its licensors. The Material
 * is protected by worldwide copyright and trace secret laws and treaty
 * provisions. No part of the Material may beused, copied, reproduced,
 * modified, published, uploaded, posted, transmitted, distributed, or
 * disclosed in any way without Intel's prior express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 *
 */

#ifndef __IA_CSS_PSA_PARAMETER_DEFS_H
#define __IA_CSS_PSA_PARAMETER_DEFS_H

/* This file contains common defines across platforms. Platform specific
 * defines are in specific header ia_css_psys_parameter_defs_dep.h
 * under respective platform folders.
 */
#include "ia_css_psa_parameter_defs_dep.h"

#define IA_CSS_PSA_KERNEL_UNSUPPORTED                  (0)
#define IA_CSS_PSA_KERNEL_TO_BE_COMPLETED              (0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_INVALID  (0)

/* Common terminal specs across platforms. For platform specific specs refer
 * ia_css_psa_parameter_defs_dep.h under respective platform folders.
 */

#define IA_CSS_PSA_KERNEL_IS_PRIMARY_WBA_WBA                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_DEMOSAIC_DEMOSAIC                    (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_GTC_CSC_CDS                          (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_SPLITTER                        (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_IEFD                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_YDS                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_TCC                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_DVS_YBIN                             (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_DVS_DVS                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_CCM                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM                              (0)

#define IA_CSS_PSA_NEEDS_SPATIAL_IN_WBA_WBA                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_DEMOSAIC_DEMOSAIC                     (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_GTC_CSC_CDS                           (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_SPLITTER                         (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_IEFD                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_YDS                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_TCC                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_DVS_YBIN                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_DVS_DVS                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_CCM                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM                               (0)

#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_WBA_WBA                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_DEMOSAIC_DEMOSAIC                    (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_GTC_CSC_CDS                          (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_SPLITTER                        (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_IEFD                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_YDS                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_TCC                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_DVS_YBIN                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_DVS_DVS                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_CCM                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM                              (0)

/* ==================== WBA_WBA specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_SECTION_COUNT               (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_0          (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_0       (0x1C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_1          (0x1C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_1       (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_WBA_WBA_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for WBA_WBA */

/* Spatial Parameter Terminal Out does not exist for WBA_WBA */

#define IA_CSS_PSA_PROGRAM_TERMINAL_WBA_WBA_SECTION_COUNT                 (0)
/* ==================== WBA_WBA specs - END ==================== */

/* ==================== GTC_CSC_CDS specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_SECTION_COUNT           (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_0      (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_0   (0x18)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_1      (0x18)
#define IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_1   (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GTC_CSC_CDS_SECTION_COUNT       (0)

/* Spatial Parameter Terminal In does not exist for GTC_CSC_CDS */

/* Spatial Parameter Terminal Out does not exist for GTC_CSC_CDS */

#define IA_CSS_PSA_PROGRAM_TERMINAL_GTC_CSC_CDS_SECTION_COUNT             (0)
/* ==================== GTC_CSC_CDS specs - END ==================== */

/* ==================== YUV1_SPLITTER specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_SPLITTER_SECTION_COUNT         (0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_SPLITTER_SECTION_COUNT     (0)

/* Spatial Parameter Terminal In does not exist for YUV1_SPLITTER */

/* Spatial Parameter Terminal Out does not exist for YUV1_SPLITTER */

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_SECTION_COUNT           (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_MAX_SIZE_SECTION_0    (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_DEST_OFFSET_SECTION_0 (0x0)
/* ==================== YUV1_SPLITTER specs - END ==================== */

/* ==================== YUV1_YDS specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_SECTION_COUNT              (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_MAX_SIZE_SECTION_0         (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_DEST_OFFSET_SECTION_0      (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_YDS_SECTION_COUNT          (0)

/* Spatial Parameter Terminal In does not exist for YUV1_YDS */

/* Spatial Parameter Terminal Out does not exist for YUV1_YDS */

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_YDS_SECTION_COUNT                (0)
/* ==================== YUV1_YDS specs - END ==================== */

/* ==================== YUV1_TCC specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_SECTION_COUNT              (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_0         (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_0      (0x0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_1         (0x2D0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_1      (0x4)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_TCC_SECTION_COUNT          (0)

/* Spatial Parameter Terminal In does not exist for YUV1_TCC */

/* Spatial Parameter Terminal Out does not exist for YUV1_TCC */

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_TCC_SECTION_COUNT                (0)
/* ==================== YUV1_TCC specs - END ==================== */

/* ==================== DVS_YBIN specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_YBIN_SECTION_COUNT        (0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_YBIN_SECTION_COUNT              (0)
/* Spatial Parameter Terminal In  does not exist for DVS_YBIN */
/* Spatial Parameter Terminal Out does not exist for DVS_YBIN */
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_SECTION_COUNT            (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_MAX_SIZE_SECTION_0       (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_DEST_OFFSET_SECTION_0    (0x0)
/* ==================== DVS_YBIN specs - END ==================== */

/* ==================== DVS_DVS specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_DVS_SECTION_COUNT             (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_DVS_SECTION_COUNT         (0)
/* Spatial Parameter Terminal In  does not exist for DVS_DVS */
/* Spatial Parameter Terminal Out does not exist for DVS_DVS */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_SECTION_COUNT               (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_MAX_SIZE_SECTION_0          (0x34)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_DEST_OFFSET_SECTION_0       (0x0)
/* ==================== DVS_DVS specs - END ==================== */

/* ==================== DVS_L0 specs - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L0_SECTION_COUNT                                   (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L0_SECTION_COUNT                                 (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT                             (0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SECTION_COUNT                      (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_COMPUTE_UNITS_PER_ELEM             (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH   (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_ELEM_SIZE_SECTION_0                (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0      (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_SLICE_SIZE_SECTION_0           (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0        IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_SLICE_SIZE_SECTION_0

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_0               (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_1          (0xC0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_1               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_1     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_1       (0xC0)
/* ==================== DVS_L0 specs - END ==================== */
/* ==================== DVS_L0 specs (as program_terminal) - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L0_SECTION_COUNT               (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L0_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L0_DEST_OFFSET_SECTION_0       (0x04B00) /* from ipu_system.rdl */
/* ==================== DVS_L0 specs (as program_terminal) - END ==================== */
/* ==================== DVS_L0 specs (as cached out terminal) - START ==================== */
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L0_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L0_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L0_DEST_OFFSET_SECTION_0       (0x00080) /* from ipu_system.rdl */
/* ==================== DVS_L0 specs (as cached out terminal) - END ==================== */

/* ==================== DVS_L1 specs - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L1_SECTION_COUNT                                   (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L1_SECTION_COUNT                                 (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT                             (0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SECTION_COUNT                      (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_COMPUTE_UNITS_PER_ELEM             (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH   (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_ELEM_SIZE_SECTION_0                (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0      (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_SLICE_SIZE_SECTION_0           (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0        IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_SLICE_SIZE_SECTION_0

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_0               (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_1          (0xB0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_1               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_1     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_1       (0xB0)
/* ==================== DVS_L1 specs - END ==================== */
/* ==================== DVS_L1 specs (as program_terminal) - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L1_SECTION_COUNT               (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L1_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L1_DEST_OFFSET_SECTION_0       (0x06340) /* from ipu_system.rdl */
/* ==================== DVS_L1 specs (as program_terminal) - END ==================== */
/* ==================== DVS_L1 specs (as cached out terminal) - START ==================== */
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L1_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L1_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L1_DEST_OFFSET_SECTION_0       (0x01C00) /* from ipu_system.rdl */
/* ==================== DVS_L1 specs (as cached out terminal) - END ==================== */

/* ==================== DVS_L2 specs - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L2_SECTION_COUNT                                   (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L2_SECTION_COUNT                                 (0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT                             (0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SECTION_COUNT                      (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_COMPUTE_UNITS_PER_ELEM             (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH   (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_ELEM_SIZE_SECTION_0                (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0      (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_SLICE_SIZE_SECTION_0           (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0        IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_SLICE_SIZE_SECTION_0

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_COMPUTE_UNITS_PER_ELEM            (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH  (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT (1)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_0               (0x28)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE * IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0       IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_1          (0x90)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_1               (0x10)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_1     (0x0)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_1       (0x90)
/* ==================== DVS_L2 specs - END ==================== */
/* ==================== DVS_L2 specs (as program_terminal) - START ==================== */
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L2_SECTION_COUNT               (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L2_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DVS_PREV_FE_L2_DEST_OFFSET_SECTION_0       (0x07600) /* from ipu_system.rdl */
/* ==================== DVS_L2 specs (as program_terminal) - END ==================== */
/* ==================== DVS_L2 specs (as cached out terminal) - START ==================== */
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L2_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L2_MAX_SIZE_SECTION_0          (IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_0)
#define IA_CSS_PSA_PARAMETER_OUT_TERMINAL_DVS_FE_L2_DEST_OFFSET_SECTION_0       (0x03200) /* from ipu_system.rdl */
/* ==================== DVS_L2 specs (as cached out terminal) - END ==================== */

/* TODO: REMOVE THE BACKWARD COMPATIBILITY */
#define IA_CSS_PSYS_PARAMETER_TERMINAL_WBA_WBA_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_WBA_WBA_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_WBA_WBA_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_WBA_WBA_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_WBA_WBA_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_WBA_WBA_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_CSC_CDS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_GTC_CSC_CDS_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_GTC_CSC_CDS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_GTC_CSC_CDS_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_GTC_CSC_CDS_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_GTC_CSC_CDS_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_SPLITTER_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_SPLITTER_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_SPLITTER_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_SPLITTER_MAX_SIZE_SECTION_0 IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_SPLITTER_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_SPLITTER_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_YDS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_YDS_MAX_SIZE_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_YDS_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_YDS_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_YDS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_YDS_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_YDS_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_YDS_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_TCC_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_TCC_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_TCC_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_TCC_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_TCC_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_TCC_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DVS_YBIN_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_YBIN_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_YBIN_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_DVS_YBIN_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_YBIN_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_YBIN_MAX_SIZE_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_YBIN_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_DVS_YBIN_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_DVS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_DVS_DVS_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DVS_DVS_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_DVS_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_DVS_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_DVS_MAX_SIZE_SECTION_0 IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_DVS_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PROGRAM_TERMINAL_DVS_DVS_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_L0_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L0_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_L0_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L0_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_ELEM_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_L1_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L1_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_L1_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L1_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_ELEM_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_NEXT_SLICE_OFFSET_SECTION_1
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DVS_L2_SECTION_COUNT IA_CSS_PSA_PROGRAM_TERMINAL_DVS_L2_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DVS_L2_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_DVS_L2_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_COMPUTE_UNITS_PER_ELEM IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_COMPUTE_UNITS_PER_ELEM
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MIN_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_0
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_SLICE_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_ELEM_SIZE_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SLICE_0_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_1 IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_NEXT_SLICE_OFFSET_SECTION_1

#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_WBA_WBA IA_CSS_PSA_KERNEL_IS_PRIMARY_WBA_WBA
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_DEMOSAIC_DEMOSAIC IA_CSS_PSA_KERNEL_IS_PRIMARY_DEMOSAIC_DEMOSAIC
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_GTC_CSC_CDS IA_CSS_PSA_KERNEL_IS_PRIMARY_GTC_CSC_CDS
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_YUV1_SPLITTER IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_SPLITTER
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_YUV1_IEFD IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_IEFD
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_YUV1_YDS IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_YDS
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_YUV1_TCC IA_CSS_PSA_KERNEL_IS_PRIMARY_YUV1_TCC
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_DVS_YBIN IA_CSS_PSA_KERNEL_IS_PRIMARY_DVS_YBIN
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_DVS_DVS IA_CSS_PSA_KERNEL_IS_PRIMARY_DVS_DVS
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_ACM_CCM IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_CCM
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_ACM_ACM IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_WBA_WBA IA_CSS_PSA_NEEDS_SPATIAL_IN_WBA_WBA
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_DEMOSAIC_DEMOSAIC IA_CSS_PSA_NEEDS_SPATIAL_IN_DEMOSAIC_DEMOSAIC
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_GTC_CSC_CDS IA_CSS_PSA_NEEDS_SPATIAL_IN_GTC_CSC_CDS
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_YUV1_SPLITTER IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_SPLITTER
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_YUV1_IEFD IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_IEFD
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_YUV1_YDS IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_YDS
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_YUV1_TCC IA_CSS_PSA_NEEDS_SPATIAL_IN_YUV1_TCC
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_DVS_YBIN IA_CSS_PSA_NEEDS_SPATIAL_IN_DVS_YBIN
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_DVS_DVS IA_CSS_PSA_NEEDS_SPATIAL_IN_DVS_DVS
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_ACM_CCM IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_CCM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_ACM_ACM IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_WBA_WBA IA_CSS_PSA_NEEDS_SPATIAL_OUT_WBA_WBA
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_DEMOSAIC_DEMOSAIC IA_CSS_PSA_NEEDS_SPATIAL_OUT_DEMOSAIC_DEMOSAIC
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_GTC_CSC_CDS IA_CSS_PSA_NEEDS_SPATIAL_OUT_GTC_CSC_CDS
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_YUV1_SPLITTER IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_SPLITTER
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_YUV1_IEFD IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_IEFD
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_YUV1_YDS IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_YDS
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_YUV1_TCC IA_CSS_PSA_NEEDS_SPATIAL_OUT_YUV1_TCC
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_DVS_YBIN IA_CSS_PSA_NEEDS_SPATIAL_OUT_DVS_YBIN
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_DVS_DVS IA_CSS_PSA_NEEDS_SPATIAL_OUT_DVS_DVS
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_ACM_CCM IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_CCM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_ACM_ACM IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM
/* END OF TODO */

#endif /* __IA_CSS_PSA_PARAMETER_DEFS_H */
