/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2019 - 2019 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel Corporation
 * or its licensors. The Material contains trade secrets and proprietary
 * and confidential information of Intel or its licensors. The Material
 * is protected by worldwide copyright and trace secret laws and treaty
 * provisions. No part of the Material may beused, copied, reproduced,
 * modified, published, uploaded, posted, transmitted, distributed, or
 * disclosed in any way without Intel's prior express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 *
 */

/*
 * TODO: Adapt this file for IPU6!
 */

#ifndef __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H
#define __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H

#include "ia_css_isa_parameter_defs.h"

/* For ISYS, ISA is the only service that can be placed in the ISYS program group.
 * Therefore, ISA kernel ids and acc ids can be named as ISYS
 */
enum ia_css_isys_kernel_id {
	IA_CSS_ISYS_KERNEL_ID_INL = 0,
	IA_CSS_ISYS_KERNEL_ID_BLC_GLOBAL,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_0,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_1,
	IA_CSS_ISYS_KERNEL_ID_BLC_SENSOR_TYPE_2,
	IA_CSS_ISYS_KERNEL_ID_PCLN,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_0,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_1,
	IA_CSS_ISYS_KERNEL_ID_LSC_SENSOR_TYPE_2,
	IA_CSS_ISYS_KERNEL_ID_DPC,
	IA_CSS_ISYS_KERNEL_ID_IDS,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AWB,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AF,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AE_CCM,
	IA_CSS_ISYS_KERNEL_ID_3A_STAT_AE,
	IA_CSS_ISYS_KERNEL_ID_DPC_PEXT,
	IA_CSS_ISYS_KERNEL_ID_STREAM_CROP,
	IA_CSS_ISYS_KERNEL_ID_WBA,
	IA_CSS_ISYS_KERNEL_ID_SIS,
	N_IA_CSS_ISYS_KERNEL_ID
};

enum ia_css_isys_acc_id {
	IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION = 0,
	IA_CSS_ISYS_ACC_ID_LSC,
	IA_CSS_ISYS_ACC_ID_GDDPC,
	IA_CSS_ISYS_ACC_ID_INPUT_DOWNSCALER,
	IA_CSS_ISYS_ACC_ID_AWB_STAT,
	IA_CSS_ISYS_ACC_ID_AF_STAT,
	IA_CSS_ISYS_ACC_ID_AE_STAT,
	IA_CSS_ISYS_ACC_ID_SIS,
	N_IA_CSS_ISYS_ACC_ID
};

#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_INL			(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_GLOBAL		(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_0	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_1	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_BLC_SENSOR_TYPE_2	(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_PCLN			(IA_CSS_ISYS_ACC_ID_INPUT_CORRECTION)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_0	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_1	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_LSC_SENSOR_TYPE_2	(IA_CSS_ISYS_ACC_ID_LSC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_DPC_V2		(IA_CSS_ISYS_ACC_ID_GDDPC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_IDS			(IA_CSS_ISYS_ACC_ID_INPUT_DOWNSCALER)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AWB		(IA_CSS_ISYS_ACC_ID_AWB_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AF		(IA_CSS_ISYS_ACC_ID_AF_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AE_CCM	(IA_CSS_ISYS_ACC_ID_AE_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_3A_STAT_AE		(IA_CSS_ISYS_ACC_ID_AE_STAT)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_DPC_PEXT		(IA_CSS_ISYS_ACC_ID_GDDPC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_STREAM_CROP		(IA_CSS_ISYS_ACC_ID_GDDPC)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_SIS_WB_SIS		(IA_CSS_ISYS_ACC_ID_SIS)
#define IA_CSS_ISYS_KERNEL_BELONGS_TO_ACC_SIS_SIS		(IA_CSS_ISYS_ACC_ID_SIS)

/* The following define the section count for the param_in/out and program terminals */
/* If used by PAL/P2P and FW we ensure compatibility at section count */
#define IA_CSS_ISYS_PARAMETER_TERMINAL_SECTION_COUNT	(				\
	IA_CSS_ISA_PARAMETER_TERMINAL_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_GLOBAL_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_BLC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_LSC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_DPC_V2_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AF_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AE_CCM_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_3A_STAT_AE_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_DPC_PEXT_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_STREAM_CROP_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_SIS_WB_SIS_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_SIS_SIS_SECTION_COUNT)

#define IA_CSS_ISYS_PARAMETER_TERMINAL_OUT_SECTION_COUNT	(			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_GLOBAL_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_BLC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_0_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_1_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_LSC_SENSOR_TYPE_2_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_V2_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AF_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AE_CCM_SECTION_COUNT +	\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_3A_STAT_AE_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_DPC_PEXT_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_STREAM_CROP_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_SIS_WB_SIS_SECTION_COUNT +		\
	IA_CSS_ISA_PARAMETER_TERMINAL_OUT_SIS_SIS_SECTION_COUNT)

#define IA_CSS_ISYS_PROGRAM_TERMINAL_SECTION_COUNT	(				\
	IA_CSS_ISA_PROGRAM_TERMINAL_INL_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_GLOBAL_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_0_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_1_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_BLC_SENSOR_TYPE_2_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_PCLN_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_0_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_1_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_LSC_SENSOR_TYPE_2_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_DPC_V2_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_IDS_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AWB_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AF_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AE_CCM_SECTION_COUNT +		\
	IA_CSS_ISA_PROGRAM_TERMINAL_3A_STAT_AE_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_DPC_PEXT_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_STREAM_CROP_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_SIS_WB_SIS_SECTION_COUNT +			\
	IA_CSS_ISA_PROGRAM_TERMINAL_SIS_SIS_SECTION_COUNT)

#define LSC_TYPE_0_SECTION_ELEMENT_SIZES_INITIALIZER	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_0_ELEM_SIZE_SECTION_0

#define LSC_TYPE_1_SECTION_ELEMENT_SIZES_INITIALIZER	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_1_ELEM_SIZE_SECTION_0

#define LSC_TYPE_2_SECTION_ELEMENT_SIZES_INITIALIZER	IA_CSS_ISYS_SPATIAL_PARAMETER_TERMINAL_IN_LSC_SENSOR_TYPE_2_ELEM_SIZE_SECTION_0

#endif /* __IA_CSS_ISYS_PARAMETER_DEFS_DEP_H */
