/*
 * Copyright (C) 2017-2018 Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Warning this file is automatically generated.
 * Any manual change here will be lost.
 */

struct IspControlInfo {
    const char* name;
    uint32_t ctrlId;
    uint32_t size;
    uint32_t tag;
};

static const IspControlInfo gIspControlInfoMap[] = {
    { "wb_gains", camera_control_isp_ctrl_id_wb_gains, sizeof(camera_control_isp_wb_gains_t), INTEL_CONTROL_ISP_WB_GAINS },
    { "color_correction_matrix", camera_control_isp_ctrl_id_color_correction_matrix, sizeof(camera_control_isp_color_correction_matrix_t), INTEL_CONTROL_ISP_COLOR_CORRECTION_MATRIX },
    { "advanced_color_correction_matrix", camera_control_isp_ctrl_id_advanced_color_correction_matrix, sizeof(camera_control_isp_advanced_color_correction_matrix_t), INTEL_CONTROL_ISP_ADVANCED_COLOR_CORRECTION_MATRIX },
    { "bxt_csc", camera_control_isp_ctrl_id_bxt_csc, sizeof(camera_control_isp_bxt_csc_t), INTEL_CONTROL_ISP_BXT_CSC },
    { "bxt_demosaic", camera_control_isp_ctrl_id_bxt_demosaic, sizeof(camera_control_isp_bxt_demosaic_t), INTEL_CONTROL_ISP_BXT_DEMOSAIC },
    { "sc_iefd", camera_control_isp_ctrl_id_sc_iefd, sizeof(camera_control_isp_sc_iefd_t), INTEL_CONTROL_ISP_SC_IEFD },
    { "see", camera_control_isp_ctrl_id_see, sizeof(camera_control_isp_see_t), INTEL_CONTROL_ISP_SEE },
    { "bnlm", camera_control_isp_ctrl_id_bnlm, sizeof(camera_control_isp_bnlm_t), INTEL_CONTROL_ISP_BNLM },
    { "tnr5_21", camera_control_isp_ctrl_id_tnr5_21, sizeof(camera_control_isp_tnr5_21_t), INTEL_CONTROL_ISP_TNR5_21 },
    { "xnr_dss", camera_control_isp_ctrl_id_xnr_dss, sizeof(camera_control_isp_xnr_dss_t), INTEL_CONTROL_ISP_XNR_DSS },
    { "gamma_tone_map", camera_control_isp_ctrl_id_gamma_tone_map, sizeof(camera_control_isp_gamma_tone_map_t), INTEL_CONTROL_ISP_GAMMA_TONE_MAP },
    { "tnr5_22", camera_control_isp_ctrl_id_tnr5_22, sizeof(camera_control_isp_tnr5_22_t), INTEL_CONTROL_ISP_TNR5_22 },
    { "tnr5_25", camera_control_isp_ctrl_id_tnr5_25, sizeof(camera_control_isp_tnr5_25_t), INTEL_CONTROL_ISP_TNR5_25 },
};

